In [ ]:
import pandas as pd
import os

df_oral = pd.read_csv("../data/open_review_datasets_improved/iclr_2025_oral.csv")
df_oral

,paper_id,title,authors,decision,paper_text,avg_rating,avg_confidence,avg_soundness,avg_presentation,avg_contribution,...,review_3_strengths,review_3_weaknesses,review_4_rating,review_4_confidence,review_4_summary,review_4_soundness,review_4_presentation,review_4_contribution,review_4_strengths,review_4_weaknesses
0,zl0HLZOJC9,Probabilistic Learning to Defer: Handling Miss...,"Cuong C. Nguyen, Thanh-Toan Do, Gustavo Carneiro",Accept (Oral),PROBABILISTIC LEARNING TO DEFER: HANDLING MISS...,8.00,2.50,3.00,3.25,3.00,...,The paper is well-written and easy to follow. ...,A key weakness is highlighted by the authors i...,8.0,3.0,This paper extends the concept of *learning to...,3.0,4.0,3.0,+ The paper addresses a research question rele...,"+ As acknowledged by the authors, the proposed..."
1,zCxGCdzreM,Kinetix: Investigating the Training of General...,"Michael Matthews, Michael Beukman, Chris Lu, J...",Accept (Oral),KINETIX: INVESTIGATING THE TRAINING OF GENERAL...,8.00,3.50,2.75,3.50,3.00,...,1. Introduces a physics engine that provides “...,1. All environments in benchmark must fall und...,8.0,3.0,"The paper introduces Kinetix, a new 2D simulat...",3.0,4.0,3.0,- Kinetix provides 66 hand-designed levels whi...,- The paper notes that as the generated enviro...
2,zBbZ2vdLzH,Joint Graph Rewiring and Feature Denoising via...,"Jonas Linkerhägner, Cheng Shi, Ivan Dokmanić",Accept (Oral),JOINT GRAPH REWIRING AND FEATURE DENOISING VIA...,8.00,2.75,3.00,2.75,2.50,...,- This paper uses cSBMs as a key framework to ...,- The proposed method involves graph structure...,8.0,2.0,The paper proposes to jointly consider graph r...,3.0,3.0,3.0,1. The proposed method is general and can be a...,1. The solution is somewhat incremental and it...
3,z5uVAKwmjf,AFlow: Automating Agentic Workflow Generation,"Jiayi Zhang, Jinyu Xiang, Zhaoyang Yu, Fengwei...",Accept (Oral),AFLOW: AUTOMATING AGENTIC WORKFLOW GENERATION ...,7.50,3.00,3.00,2.50,3.50,...,Novel Approach: AFLOW’s integration of MCTS wi...,Limited Scope and Generalizability: The paper ...,8.0,3.0,"The paper introduces Aflow, a new automatic wo...",3.0,3.0,4.0,"Overall, this paper is clear, well-motivated a...",The paper could benefit from discussions with ...
4,xyfb9HHvMe,DSPO: Direct Score Preference Optimization for...,"Huaisheng Zhu, Teng Xiao, Vasant G Honavar",Accept (Oral),DSPO: DIRECT SCORE PREFERENCE OPTIMIZATION FOR...,6.67,3.67,3.33,2.67,3.33,...,1. The first method that fine-tunes diffusion ...,1. Figure 3 looks cramped; the equations are p...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,1aF2D2CPHi,Open-Vocabulary Customization from CLIP via Da...,"Yongxian Wei, Zixuan Hu, Li Shen, Zhenyi Wang,...",Accept (Oral),OPEN-VOCABULARY CUSTOMIZATION FROM CLIP VIA DA...,8.00,3.50,3.25,2.75,3.25,...,This paper presents a novel approach to open-v...,1. While Figure 1 provides a good overview of ...,8.0,3.0,The paper presents a novel approach for open-v...,3.0,2.0,3.0,The paper provides a meaningful contribution t...,The paper's writing could be improved for clar...
209,1HCN4pjTb4,Wide Neural Networks Trained with Weight Decay...,"Arthur Jacot, Peter Súkeník, Zihan Wang, Marco...",Accept (Oral),WIDE NEURAL NETWORKS TRAINED WITH WEIGHT DECAY...,8.00,3.00,3.50,2.75,3.25,...,- The authors provide the first theoretical an...,- My main concern with the paper is the writin...,8.0,2.0,This paper presents an interesting theoretical...,4.0,3.0,4.0,This work provides an interesting theoretical ...,"In my opinion, this is a solid paper and I can..."
210,1CLzLXSFNn,TimeMixer++: A General Time Series Pattern Mac...,"Shiyu Wang, Jiawei LI, Xiaoming Shi, Zhou Ye, ...",Accept (Oral),TIMEMIXER++: A GENERAL TIME SERIES PATTERN MAC...,8.00,4.33,3.00,3.33,3.33,...,S1. The proposed model captures both short- an...,W1. There is little exploration of scaling of ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
211,0ctvBgKFgc,ProtComposer: Compositional Protein Structure ...,"Hannes Stark, Bowen Jing, Tomas Geffner, Jason...",Accept (Oral),PROTCOMPOSER: COMPOSITIONAL PROTEIN STRUCTURE ...,8.00,3.50,3.50,3.75,3.25,...,**[Clarity & Quality]** - The manuscript is we...,**[Clarity]** - Some design choices and model ...,8.0,3.0,This paper proposes a framework to generate pr...,4.0,4.0,3.0,"This paper is well motivated, formulated, writ...",How is sequence design performance? What I und...
212,07yvxWDSla,Synthetic continued pretraining,"Zitong Yang, Neil Band, Shuangping Li, Emmanue...",Accept (Oral),SYNTHETIC CONTINUED PRETRAINING Zitong Yang∗ D...,8.00,3.50,3.50,3.25,2.75,...,The paper does a good job at demonstrating the...,The work relies on commercial and closed-sourc...,8.0,4.0,This paper addresses the problem of data ineff...,4.0,4.0,3.0,* The problem the work addresses is important....,While the experiments focus on the QuALITY cor...

In [20]:
df_sample = df_oral.sample(n=10)
df_sample

,paper_id,title,authors,decision,paper_text,avg_rating,avg_confidence,avg_soundness,avg_presentation,avg_contribution,...,review_3_strengths,review_3_weaknesses,review_4_rating,review_4_confidence,review_4_summary,review_4_soundness,review_4_presentation,review_4_contribution,review_4_strengths,review_4_weaknesses
54,mtJSMcF3ek,Mind the Gap: Examining the Self-Improvement C...,"Yuda Song, Hanlin Zhang, Carson Eisenach, Sham...",Accept (Oral),MIND THE GAP: EXAMINING THE SELF-IMPROVEMENT C...,7.0,3.75,3.00,3.00,3.00,...,* The proposed measure (gv-gap) is clearly def...,* While the definition of the gv-gap is pretty...,6.0,4.0,The paper investigates the concept of self-imp...,3.0,3.0,3.0,1. The research focus of this paper is commend...,### Deficiencies in Expression 1. The paper la...
50,ny8T8OuNHe,Ctrl-Adapter: An Efficient and Versatile Frame...,"Han Lin, Jaemin Cho, Abhay Zala, Mohit Bansal",Accept (Oral),CTRL-ADAPTER: AN EFFICIENT AND VERSATILE FRAME...,7.0,3.25,3.25,2.75,3.25,...,+ The presentation and writing quality of this...,+ While skipping latents can increase efficien...,8.0,3.0,The paper proposes an efficient method for ada...,4.0,2.0,4.0,- The results proposed in the paper are intere...,- Poor presentation: the main paper is packed ...
183,AP0ndQloqR,Geometry of Neural Reinforcement Learning in C...,"Saket Tiwari, Omer Gottesman, George Konidaris",Accept (Oral),GEOMETRY OF NEURAL REINFORCEMENT LEARNING IN C...,7.5,2.50,3.00,2.75,3.25,...,- Strong theoretical insights: The authors loo...,- The mathematical presentation is too complex...,8.0,2.0,This paper studies the Manifold hypothesis for...,4.0,3.0,4.0,The paper is well-written and rigorous. The an...,I don’t have any major comments on the weaknes...
143,N8Oj1XhtYZ,SANA: Efficient High-Resolution Text-to-Image ...,"Enze Xie, Junsong Chen, Junyu Chen, Han Cai, H...",Accept (Oral),SANA: EFFICIENT HIGH-RESOLUTION IMAGE SYN- THE...,8.5,4.25,3.25,3.25,2.75,...,1. Innovative Efficiency Strategies: SANA’s in...,Limited Ablation in Model Design: While SANA c...,10.0,5.0,"The paper presents Sana, a cutting-edge text-t...",4.0,4.0,3.0,This work demonstrates its originality through...,1. The Gemma2-2B-IT model in Table 9 needs to ...
53,mtSSFiqW6y,Judge Decoding: Faster Speculative Sampling Re...,"Gregor Bachmann, Sotiris Anagnostidis, Albert ...",Accept (Oral),JUDGE DECODING: FASTER SPECULATIVE SAMPLING RE...,8.0,3.50,3.25,3.75,3.25,...,The paper is well-written. The argument is cle...,I do not see significant weakness. But the sen...,8.0,3.0,"The submission proposes Judge Decoding (JD), a...",4.0,4.0,4.0,"* Clear presentation, covering both technical ...","* Some of the results (e.g., lack of agreement..."
19,v593OaNePQ,Learning to Search from Demonstration Sequences,"Dixant Mittal, Liwei Kang, Wee Sun Lee",Accept (Oral),LEARNING TO SEARCH FROM DEMONSTRATION SEQUENCE...,8.0,3.75,3.50,2.75,3.00,...,- Builds on TreeQN and improves a significant ...,- Seeing how the approach handles large action...,10.0,4.0,This paper introduces the Differentiable Tree ...,4.0,4.0,3.0,1. Novel Architecture: The paper proposes a no...,1. Limited to Deterministic Environments: The ...
69,is4nCVkSFA,Can Neural Networks Achieve Optimal Computatio...,"Siyu Chen, Beining Wu, Miao Lu, Zhuoran Yang, ...",Accept (Oral),C A N N E U R A L N E T W O R K S AC H I E V E...,7.5,3.50,3.00,3.25,3.00,...,The paper has solid technical contributions an...,* The original motivation as stated in the abs...,8.0,3.0,This paper investigates the sample complexity ...,3.0,4.0,3.0,- Gaussian single index models have received a...,"- The algorithm requires a gradient oracle, wh..."
192,6s5uXNWGIh,MLE-bench: Evaluating Machine Learning Agents ...,"Jun Shern Chan, Neil Chowdhury, Oliver Jaffe, ...",Accept (Oral),MLE-BENCH: EVALUATING MACHINE LEARNING AGENTS ...,8.0,3.75,3.25,3.25,3.25,...,The experimental results presented in the pape...,"Please see the following suggestions that, in ...",8.0,3.0,"This paper introduces MLE-bench, which is a be...",3.0,3.0,3.0,"Originality. To my knowledge, this benchmark i...",1. There seems to be an issue with Figure 2. I...
207,1pXzC30ry5,RMP-SAM: Towards Real-Time Multi-Purpose Segme...,"Shilin Xu, Haobo Yuan, Qingyu Shi, Lu Qi, Jing...",Accept (Oral),RMP-SAM: TOWARDS REAL-TIME MULTI-PURPOSE SEGME...,7.5,3.50,3.00,2.50,2.75,...,1.Demonstrates impressive performance and infe...,"1.Based on existing technology development, th...",8.0,3.0,"The paper presents a real-time, versatile segm...",3.0,3.0,3.0,1. The model achieves multi-purpose segmentati...,1. The paper lacks a detailed comparison with ...
49,o2Igqm95SJ,CAX: Cellular Automata Accelerated in JAX,"Maxence Faldor, Antoine Cully",Accept (Oral),CAX: CELLULAR AUTOMATA ACCELERATED IN JAX Maxe...,8.0,3.75,3.00,3.50,2.75,...,The article is clearly written and makes a com...,A question I had in reviewing this was its rel...,8.0,4.0,The paper present a new library that can model...,2.0,3.0,3.0,The issue the library tackles is impactful. CA...,The paper stresses some standard library featu...

In [22]:
# Caminho completo do arquivo
caminho = "../data/open_review_datasets_to_prompt_tests/iclr_2025_oral_sorted.csv"

# Cria o diretório se não existir
os.makedirs(os.path.dirname(caminho), exist_ok=True)

# Salva o DataFrame no CSV
df_sample.to_csv(caminho, index=False)

In [23]:
df_poster = pd.read_csv("../data/open_review_datasets_improved/iclr_2025_poster.csv")
df_poster

,paper_id,title,authors,decision,paper_text,avg_rating,avg_confidence,avg_soundness,avg_presentation,avg_contribution,...,review_3_strengths,review_3_weaknesses,review_4_rating,review_4_confidence,review_4_summary,review_4_soundness,review_4_presentation,review_4_contribution,review_4_strengths,review_4_weaknesses
0,zxg6601zoc,Re-Imagining Multimodal Instruction Tuning: A ...,"Yiyang Liu, James Chenhao Liang, Ruixiang Tang...",Accept (Poster),RE-IMAGINING MULTIMODAL INSTRUCTION TUNING: A ...,5.75,3.75,2.75,2.75,2.75,...,"- MRT is intuitive, simple, and effective. It ...",- The rank parameter is integral to MRT’s perf...,6.0,4.0,The paper proposes a novel Multimodal Represen...,3.0,3.0,3.0,1.\tThe overall writing is clear. 2.\tThe idea...,"1.\tThere are some typos. For example, ##hu202..."
1,zxO4WuVGns,Inverse decision-making using neural amortized...,"Dominik Straub, Tobias F. Niehues, Jan Peters,...",Accept (Poster),INVERSE DECISION-MAKING USING NEURAL AMOR- TIZ...,6.00,2.33,2.67,3.00,3.00,...,This paper address an important bottleneck in ...,"In this work, the proposed approach aims to in...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,zvaiz3FjA9,Designing Concise ConvNets with Columnar Stages,"Ashish Kumar, Jaesik Park",Accept (Poster),DESIGNING CONCISE CONVNETS WITH COLUMNAR STAGE...,6.00,4.00,3.00,3.00,3.00,...,This paper revisits some of the fundamental de...,"Please refer to the questions section, where s...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,zu7cBTPsDb,MVTokenFlow: High-quality 4D Content Generatio...,"Hanzhuo Huang, Yuan Liu, Ge Zheng, Jiepeng Wan...",Accept (Poster),MVTOKENFLOW: HIGH-QUALITY 4D CONTENT GEN- ERAT...,6.00,4.50,2.50,2.25,2.25,...,1) It is natural to incorporate knowledge of v...,1. Token Propagation: As illustrated in Sectio...,6.0,4.0,This paper presents a method by which multivie...,3.0,3.0,3.0,* method seems relatively clean without unneed...,"* Minor point, but I'd recommend the authors a..."
4,zqzsZ5cXbB,Let the Code LLM Edit Itself When You Edit the...,"Zhenyu He, Jun Zhang, Shengjie Luo, Jingjing X...",Accept (Poster),LET THE CODE LLM EDIT ITSELF WHEN YOU EDIT THE...,5.50,3.25,2.75,3.00,2.75,...,1. The paper is well-written and easy to under...,1. The results are limited to 1 dataset and 1 ...,3.0,4.0,This paper introduces a technique to update th...,1.0,3.0,2.0,The paper effectively outlines the real-time e...,**Limited Technical Novelty**: The mathematica...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3110,09FiNmvNMw,Divide and Translate: Compositional First-Orde...,"Hyun Ryu, Gyeongman Kim, Hyemin S. Lee, Eunho ...",Accept (Poster),DIVIDE AND TRANSLATE: COMPOSITIONAL FIRST- ORD...,5.67,3.67,2.67,1.67,2.33,...,- The paper presents a new approach by breakin...,- The approach is primarily applicable to prob...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3111,0823rvTIhs,Weakly-Supervised Affordance Grounding Guided ...,"Peiran Xu, Yadong MU",Accept (Poster),WEAKLY-SUPERVISED AFFORDANCE GROUNDING GUIDED ...,6.25,3.25,3.25,3.25,3.00,...,"- The problem is important and well-motivated,...",The choice of CLIP as the vision encoder could...,6.0,3.0,The proposed framework for weakly supervised a...,3.0,3.0,3.0,1) The paper is clearly written and easy to fo...,My biggest concern lies in the experimental se...
3112,03EkqSCKuO,Port-Hamiltonian Architectural Bias for Long-R...,"Simon Heilig, Alessio Gravina, Alessandro Tren...",Accept (Poster),PORT-HAMILTONIAN ARCHITECTURAL BIAS FOR LONG-R...,7.00,2.67,3.33,3.00,2.33,...,"Overall, the idea of using Hamilton's dynamics...",1. Novelty is incremental: - Builds on existin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3113,02haSpO453,VILA-U: a Unified Foundation Model Integrating...,"Yecheng Wu, Zhuoyang Zhang, Junyu Chen, Haotia...",Accept (Poster),VILA-U: A UNIFIED FOUNDATION MODEL INTEGRAT- I...,6.50,4.25,3.00,3.00,3.00,...,1. VILA-U introduces a unified framework that ...,1. Missing the clarification between VILA-U an...,8.0,4.0,"- The paper presents VILA-U, a unified model f...",4.0,3.0,3.0,- The paper's most interesting contribution is...,"- The method chooses RQ-VAE for efficiency, bu..."
3114,029hDSVoXK,Dynamic Neural Fortresses: An Adaptive Shield ...,"Siyu Luan, Zhenyi Wang, Li Shen, Zonghua Gu, C...",Accept (Poster),DYNAMIC NEURAL FORTRESSES: AN ADAPTIVE SHIELD ...,6.50,3.25,2.75,2.50,3.00,...,* The first defense framework simultaneously o...,* The claims regarding the protection of model...,6.0,3.0,This paper introduces a new defense against mo...,3.0,3.0,3.0,+ Good motivation. The authors adopt multi-exi...,"- The assumption of attack data are OOD data, ..."

In [26]:
df_sample = df_poster.sample(n=10)
df_sample

,paper_id,title,authors,decision,paper_text,avg_rating,avg_confidence,avg_soundness,avg_presentation,avg_contribution,...,review_3_strengths,review_3_weaknesses,review_4_rating,review_4_confidence,review_4_summary,review_4_soundness,review_4_presentation,review_4_contribution,review_4_strengths,review_4_weaknesses
2464,CGhgB8Kz8i,"Innovative Thinking, Infinite Humor: Humor Res...","Han Wang, Yilin Zhao, Dian Li, Xiaohan Wang, s...",Accept (Poster),"INNOVATIVE THINKING, INFINITE HUMOR: HUMOR RES...",5.00,3.50,2.75,2.25,2.25,...,This paper introduces the Creative Leap of Str...,1. This paper is very difficult to read and un...,6.0,3.0,This paper introduces the Creative Leap of Str...,3.0,3.0,3.0,"- The paper presents the CLoST framework, a no...",- The inherent subjectivity of humor presents ...
917,i8LCUpKvAz,Minimax Optimal Reinforcement Learning with Qu...,"Harin Lee, Min-hwan Oh",Accept (Poster),MINIMAX OPTIMAL REINFORCEMENT LEARNING WITH QU...,7.00,3.75,3.25,3.00,3.00,...,"- To my knowledge, it is the first result on a...",- The algorithm cannot adapt to deterministic ...,6.0,4.0,The paper studies reinforcement learning in ta...,3.0,3.0,3.0,"1. Making provably-efficient RL algorithms, ev...",My main concern is about the way these novel b...
451,rsZwwjYHuD,Self-Introspective Decoding: Alleviating Hallu...,"Fushuo Huo, Wenchao Xu, Zhong Zhang, Haozhao W...",Accept (Poster),SELF-INTROSPECTIVE DECODING: ALLEVIATING HALLU...,6.25,4.00,2.75,3.00,2.75,...,- The proposed approach does not require addit...,- The paper does not present the results on di...,8.0,3.0,This manuscript proposes to solve the hallucin...,3.0,3.0,3.0,1. The proposed SID with its key component: Co...,1. The proposed SID is performed on pre-traine...
2764,6lB5qtdYAg,HD-Painter: High-Resolution and Prompt-Faithfu...,"Hayk Manukyan, Andranik Sargsyan, Barsegh Atan...",Accept (Poster),HD-PAINTER: HIGH-RESOLUTION AND PROMPT- FAITHF...,6.00,3.25,3.00,2.50,3.00,...,The discussion about prompt neglect is promisi...,Some discussion and analysis should be include...,6.0,3.0,The authors introduced Prompt-Aware Introverte...,3.0,3.0,3.0,* The writing is clear to understand with deta...,Some questions below * Would this method be ea...
1314,aIMi2lOKIn,Diff3DS: Generating View-Consistent 3D Sketch ...,"Yibo Zhang, Lihong Wang, Changqing Zou, Tieru ...",Accept (Poster),DIFF3DS: GENERATING VIEW-CONSISTENT 3D SKETCH ...,6.50,3.75,3.00,3.25,2.50,...,* Covers multiple aspects of differentiable re...,* The z-ordering of Bézier curves in Section 4...,6.0,4.0,"The authors present Diff3DS, a framework for o...",3.0,4.0,3.0,Strengths: - Through the use of score distilla...,Weaknesses: - The main contribution of this wo...
693,meKEKDhdnx,Preble: Efficient Distributed Prompt Schedulin...,"Vikranth Srivatsa, Zijian He, Reyna Abhyankar,...",Accept (Poster),PREBLE: EFFICIENT DISTRIBUTED PROMPT SCHEDULIN...,7.00,3.50,3.25,2.75,2.75,...,- The authors propsed a first system to addres...,- Althought the paper claim strong scalability...,6.0,4.0,The paper presents Preble which optimize for p...,3.0,2.0,2.0,The paper achieved performance improvements co...,The major concern is that contribution and nov...
2504,BUj9VSCoET,Efficient Residual Learning with Mixture-of-Ex...,"Ziye Huang, Haoqi Yuan, Yuhui Fu, Zongqing Lu",Accept (Poster),EFFICIENT RESIDUAL LEARNING WITH MIXTURE-OF- E...,7.00,4.25,3.25,3.75,3.25,...,- This work tackles an important problem in le...,- The definitions of different reward function...,8.0,5.0,This work combines concepts from residual poli...,4.0,4.0,3.0,1. The authors propose a residual mixture-of-e...,1. The paper lacks any real-world experiments....
125,xPxHQHDH2u,Reflective Gaussian Splatting,"Yuxuan Yao, Zixuan Zeng, Chun Gu, Xiatian Zhu,...",Accept (Poster),"REFLECTIVE GAUSSIAN SPLATTING Yuxuan Yao1∗, Zi...",6.50,4.25,2.75,3.50,2.50,...,"- Rendering quality is excellent, and reconstr...",- The contribution of this paper may lack nove...,8.0,4.0,"Though powerful in novel view synthesis, vanil...",3.0,4.0,3.0,"1. By extracting explicit geometry, the paper ...",1. The effectiveness of inter-reflection techn...
1218,c54apoozCS,On Statistical Rates of Conditional Diffusion ...,"Jerry Yao-Chieh Hu, Weimin Wu, Yi-Chen Lee, Yu...",Accept (Poster),ON STATISTICAL RATES OF CONDITIONAL DIFFUSION ...,6.25,2.75,3.25,2.75,2.50,...,- The paper provides a detailed theoretical fr...,A general weakness of this paper is its relian...,6.0,3.0,This paper studies the statistical rates of ap...,3.0,3.0,2.0,The paper is original in its theoretical appro...,1. Some results seem to suffer from the curse ...
999,gY08Ou8EL7,LIFe-GoM: Generalizable Human Rendering with L...,"Jing Wen, Alex Schwing, Shenlong Wang",Accept (Poster),LIFE-GOM: GENERALIZABLE HUMAN RENDERING WITH L...,7.00,4.00,3.00,3.25,3.00,...,The presented method has the following strengt...,The paper has the following weakness: - Missin...,6.0,5.0,This paper tackles the challenge of creating a...,3.0,3.0,3.0,- The feedback mechanism in this generalizable...,- The model does not appear to have been train...

In [27]:
# Caminho completo do arquivo
caminho = "../data/open_review_datasets_to_prompt_tests/iclr_2025_poster_sorted.csv"

# Cria o diretório se não existir
os.makedirs(os.path.dirname(caminho), exist_ok=True)

# Salva o DataFrame no CSV
df_sample.to_csv(caminho, index=False)

In [28]:
df_spotlight = pd.read_csv("../data/open_review_datasets_improved/iclr_2025_spotlight.csv")
df_spotlight

,paper_id,title,authors,decision,paper_text,avg_rating,avg_confidence,avg_soundness,avg_presentation,avg_contribution,...,review_3_strengths,review_3_weaknesses,review_4_rating,review_4_confidence,review_4_summary,review_4_soundness,review_4_presentation,review_4_contribution,review_4_strengths,review_4_weaknesses
0,ztzZDzgfrh,ReDeEP: Detecting Hallucination in Retrieval-A...,"ZhongXiang Sun, Xiaoxue Zang, Kai Zheng, Jun X...",Accept (Spotlight),REDEEP: DETECTING HALLUCINATION IN RETRIEVAL-A...,7.33,3.67,3.33,2.67,3.33,...,- Authors provide a straightforward method to ...,## Lack of justification for PKS and ECS ### N...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,z8sxoCYgmd,LOKI: A Comprehensive Synthetic Data Detection...,"Junyan Ye, Baichuan Zhou, Zilong Huang, Junan ...",Accept (Spotlight),LOKI: A COMPREHENSIVE SYNTHETIC DATA DE- TECTI...,8.00,4.50,3.00,3.25,3.25,...,The paper is well-written and easy to follow. ...,"While the differentiated modalities, categorie...",8.0,5.0,The paper introduces a novel benchmark designe...,3.0,3.0,3.0,"+ LOKI is a novel, multimodal dataset. + The p...",- The benchmark lacks a robustness test agains...
2,ywFOSIT9ik,Revisiting Zeroth-Order Optimization: Minimum-...,"Shaocong Ma, Heng Huang",Accept (Spotlight),REVISITING ZEROTH-ORDER OPTIMIZATION: MINIMUM-...,6.50,2.75,3.00,3.25,2.75,...,This paper explores the two-point zeroth-order...,I don't think the study over problem Eq. (3) i...,6.0,2.0,This paper studies the two-point zeroth-order ...,3.0,3.0,3.0,"To the best of the reviewer's understanding, t...",This can be closer to a question than a weakne...
3,ykuc5q381b,BRIGHT: A Realistic and Challenging Benchmark ...,"Hongjin SU, Howard Yen, Mengzhou Xia, Weijia S...",Accept (Spotlight),BRIGHT: A REALISTIC AND CHALLENGING BENCH- MAR...,7.50,3.75,3.25,3.50,3.25,...,- The benchmark is challenging and has the pot...,- Detailed analysis of results is lacking and ...,8.0,4.0,"The paper presents **BRIGHT**, a benchmark for...",3.0,3.0,3.0,- The data collection pipeline is thorough and...,- It could have been helpful to add a quantita...
4,yfW1x7uBS5,Adversarial Perturbations Cannot Reliably Prot...,"Robert Hönig, Javier Rando, Nicholas Carlini, ...",Accept (Spotlight),ADVERSARIAL PERTURBATIONS CANNOT RELIABLY PROT...,7.50,4.00,3.00,3.50,3.00,...,1. While it was anticipated that prominent sty...,1. The work has limited novelty since it was p...,8.0,4.0,The authors critically revisit the current eff...,4.0,3.0,3.0,- The paper is well-written and easy to follow...,Clarification: - The title of this paper is 'A...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,0fJfVOSUra,"ThunderKittens: Simple, Fast, and $\textit{Ado...","Benjamin Frederick Spector, Simran Arora, Aary...",Accept (Spotlight),"THUNDERKITTENS: SIMPLE, FAST, AND Adorable KER...",7.50,4.25,3.00,3.00,3.00,...,The authors demonstrate significant improvemen...,"-\tThe application appears limited in scope, w...",8.0,4.0,The paper proposes a new programming library f...,3.0,3.0,3.0,* The paper proposes methods at different leve...,* The paper has not discussed the tunning over...
376,0bmGL4q7vJ,Multi-modal Agent Tuning: Building a VLM-Drive...,"Zhi Gao, Bofei Zhang, Pengxiang Li, Xiaojian M...",Accept (Spotlight),MULTI-MODAL AGENT TUNING: BUILDING A VLM- DRIV...,7.50,3.25,3.00,3.25,2.75,...,1. Innovation in Multi-Modal Interaction: The ...,1. Interpretability: While the approach demons...,6.0,4.0,This paper proposes a method for multi-modal a...,3.0,3.0,3.0,1) The idea of using an LLM to separately gene...,1) Verifying the output of an LLM by the LLM i...
377,04qx93Viwj,Holistically Evaluating the Environmental Impa...,"Jacob Morrison, Clara Na, Jared Fernandez, Tim...",Accept (Spotlight),HOLISTICALLY EVALUATING THE ENVIRONMENTAL IMPA...,7.33,4.00,3.33,3.00,3.33,...,1. The paper raises very important concerns ab...,1. While some of the calculations are clear an...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
378,03OkC0LKDD,Adaptive Gradient Clipping for Robust Federate...,"Youssef Allouah, Rachid Guerraoui, Nirupam Gup...",Accept (Spotlight),ADAPTIVE GRADIENT CLIPPING FOR ROBUST FEDER- A...,7.50,3.75,2.50,3.00,3.50,...,The paper proposes an adaptive method that mai...,Considering the critical role that numerical e...,8.0,4.0,This paper proposes a novel strategy called Ad...,3.0,3.0,4.0,1. This paper is generally well-written. 2. Th...,Although the proposed ARC strategy is generall...
379,00SnKBGTsz,DataEnvGym: Data Generation Agents in Teacher ...,"Zaid Khan, Elias Stengel-Eskin, Jaemin Cho, Mo...",Accept (Spotlight),DATAENVGYM: DATA GENERATION AGENTS IN TEACHER ...,7.50,3.75,3.25,2.75,3.25,...,This paper presents a novel and insightful per...,The experiment part should be conducted more t...,8.0,4.0,This paper introduces Gym environments for dat...,4.0,3.0,4.0,- Tackle a timely and interesting problem. - P...,* The paper is currently dense and difficult t...

In [43]:
df_sample = df_spotlight.sample(n=10)
df_sample

,paper_id,title,authors,decision,paper_text,avg_rating,avg_confidence,avg_soundness,avg_presentation,avg_contribution,...,review_3_strengths,review_3_weaknesses,review_4_rating,review_4_confidence,review_4_summary,review_4_soundness,review_4_presentation,review_4_contribution,review_4_strengths,review_4_weaknesses
102,jCPak79Kev,AnalogGenie: A Generative Engine for Automatic...,"Jian Gao, Weidong Cao, Junyi Yang, Xuan Zhang",Accept (Spotlight),ANALOGGENIE: A GENERATIVE ENGINE FOR AUTO- MAT...,7.50,3.75,3.25,3.25,3.50,...,1. The authors propose an innovative RAG repre...,The experimental part over-emphasized the perf...,8.0,4.0,"The paper introduces AnalogGenie, a generative...",3.0,3.0,4.0,Strength: * The idea of transferring the analo...,Weakness: * The main weakness of this paper is...
11,xaYlO03tIk,Stem-OB: Generalizable Visual Imitation Learni...,"Kaizhe Hu, Zihang Rui, Yao He, Yuyao Liu, Pu H...",Accept (Spotlight),Stem-OB: GENERALIZABLE VISUAL IMITATION LEARNI...,7.50,3.25,3.00,3.00,3.25,...,"- The idea is, as the authors write, 'simple y...",- [**update after discussion: this point was f...,6.0,3.0,"This paper introduces Stem-OB, a method that e...",3.0,2.0,3.0,* This paper focuses on enhancing the robustne...,* I found the structure of this paper somewhat...
25,vVCHWVBsLH,Decomposition Polyhedra of Piecewise Linear Fu...,"Marie-Charlotte Brandenburg, Moritz Leo Grillo...",Accept (Spotlight),Decomposition Polyhedra of Piecewise Linear Fu...,7.25,3.00,3.25,3.00,2.75,...,The DC representation of a general CPWL functi...,While the pieces are assumed to be fixed in ad...,5.0,3.0,This paper deals with the following problem: g...,3.0,2.0,2.0,The problem of decomposing CPWL functions as t...,The assumption that the DC decomposition shoul...
241,MtDd7rWok1,Anti-Exposure Bias in Diffusion Models,"Junyu Zhang, Daochang Liu, Eunbyung Park, Shic...",Accept (Spotlight),ANTI-EXPOSURE BIAS IN DIFFUSION MODELS Junyu Z...,7.00,3.50,2.75,3.00,2.75,...,1. This paper is well-structured and presents ...,"Overall, from my perspective, I think this pap...",6.0,4.0,"In this paper, the authors begin by addressing...",3.0,3.0,3.0,1.The insight is interesting. 2.The method is ...,1.The architecture of the prompt learning netw...
324,8bjspmAMBk,Quality Measures for Dynamic Graph Generative ...,"Ryien Hosseini, Filippo Simini, Venkatram Vish...",Accept (Spotlight),QUALITY MEASURES FOR DYNAMIC GRAPH GENERATIVE ...,7.50,2.25,3.00,3.00,3.00,...,S1: Unified Metric for Temporal Dynamics: The ...,See questions.,8.0,3.0,The primary motivation behind the proposed wor...,3.0,3.0,3.0,1. Novel Approach to Evaluating Dynamic Graph ...,1. In 4.1 evaluation: Are all the types of per...
112,hUb2At2DsQ,Rethinking and Improving Autoformalization: To...,"Qi Liu, Xinhao Zheng, Xudong Lu, Qinxiang Cao,...",Accept (Spotlight),RETHINKING AND IMPROVING AUTOFORMALIZATION: TO...,7.50,3.50,3.25,3.50,3.00,...,1.\tThe design of the training protocol seems ...,Some certain details can be included to make t...,8.0,3.0,The paper addresses a few key challenges in th...,4.0,4.0,3.0,"1. The paper is very well-written, easy to fol...",While I don't see any major weakness in the pa...
28,uvHmnahyp1,SynFlowNet: Design of Diverse and Novel Molecu...,"Miruna Cretu, Charles Harris, Ilia Igashov, Ar...",Accept (Spotlight),SYNFLOWNET: DESIGN OF DIVERSE AND NOVEL MOLECU...,7.50,4.00,2.75,3.00,3.00,...,1. The use of the GFlowNet improves both diver...,1. The conclusions of some experiments are arg...,8.0,4.0,It was a pleasure to review this paper on synt...,4.0,4.0,3.0,* The background and related work section was ...,* I searched throughout the paper and in the s...
346,4HRRcqE9SU,ND-SDF: Learning Normal Deflection Fields for ...,"Ziyu Tang, Weicai Ye, Yifan Wang, Di Huang, Hu...",Accept (Spotlight),ND-SDF: LEARNING NORMAL DEFLECTION FIELDS FOR ...,7.50,4.25,2.75,3.00,2.75,...,1. The paper is well-written and easy to follo...,1. The bad quality normal prior problem seems ...,8.0,3.0,This paper presents a pipeline for multi-view ...,3.0,3.0,3.0,"- The proposed normal deflection fields, which...",- Using unbiased volume rendering for thin str...
323,8oCrlOaYcc,"Don't flatten, tokenize! Unlocking the key to ...","Ghada Sokar, Johan Samir Obando Ceron, Aaron C...",Accept (Spotlight),"DON’T FLATTEN, TOKENIZE! UNLOCKING THE KEY TO ...",7.25,3.50,2.75,3.25,2.75,...,- Results are significant with small variance ...,- Authors should add a section that explains w...,8.0,3.0,This paper investigates the key factors that m...,3.0,3.0,3.0,- The paper is well-written and easy to read. ...,The main concern is the generality of the clai...
213,R1hIXdST22,Towards General-Purpose Model-Free Reinforceme...,"Scott Fujimoto, Pierluca D'Oro, Amy Zhang, Yua...",Accept (Spotlight),TOWARDS GENERAL-PURPOSE MODEL-FREE REINFORCEME...,7.50,3.50,3.00,3.25,3.00,...,* The paper is very well presented and has a c...,## Hyperparameters One of the primary aims of ...,6.0,3.0,"The authors propose a generalist, model-free d...",3.0,2.0,3.0,1. MR.Q combines various state-of-the-art tech...,The theoretical motivation presented by the au...

In [44]:
# Caminho completo do arquivo
caminho = "../data/open_review_datasets_to_prompt_tests/iclr_2025_spotlight_sorted.csv"

# Cria o diretório se não existir
os.makedirs(os.path.dirname(caminho), exist_ok=True)

# Salva o DataFrame no CSV
df_sample.to_csv(caminho, index=False)

In [45]:
df_rejected = pd.read_csv("../data/open_review_datasets_improved/iclr_2025_rejected.csv")
df_rejected

,paper_id,title,authors,decision,paper_text,avg_rating,avg_confidence,avg_soundness,avg_presentation,avg_contribution,...,review_3_strengths,review_3_weaknesses,review_4_rating,review_4_confidence,review_4_summary,review_4_soundness,review_4_presentation,review_4_contribution,review_4_strengths,review_4_weaknesses
0,zzR1Uskhj0,High Probability Bounds for Cross-Learning Con...,"Ruiyuan Huang, Zengfeng Huang",Reject,HIGH PROBABILITY BOUND FOR CROSS-LEARNING CONT...,6.25,3.50,3.50,3.00,3.00,...,- The paper proves a high probability lower bo...,Can the reduction in [1] be used to map the mu...,5.0,3.0,This paper addresses the challenge of achievin...,3.0,3.0,3.0,The paper proposes a new look at an existing p...,See questions.
1,zyGrziIVdE,Exploration by Running Away from the Past,"Paul-Antoine LE TOLGUENEC, Yann Besse, Florent...",Reject,EXPLORATION BY RUNNING AWAY FROM THE PAST Anon...,3.50,3.75,2.00,2.75,2.25,...,1. The problem addressed is important to the c...,"1. In Section 2, different justifications for ...",3.0,4.0,The paper proposes RAMP (Running away from the...,2.0,3.0,2.0,Though the problem of state space exploration ...,"Despite the strengths discussed above, I have ..."
2,zxqdVo9FjY,Generalization for Least Squares Regression wi...,"Jiping Li, Rishi Sonthalia",Reject,GENERALIZATION FOR LEAST SQUARES REGRESSION WI...,4.75,3.50,2.50,2.50,2.00,...,1. They construct two linear regression proble...,"1. They reference the work of Moniri et al., b...",3.0,4.0,Motivated by a recent work studying two-layer ...,2.0,1.0,1.0,* The motivation for this paper is good since ...,* The presentation in this paper is not good +...
3,zxbQLztmwb,Emergent Symbol-Like Number Variables in Artif...,"Satchel Grant, Noah Goodman, James Lloyd McCle...",Reject,EMERGENT SYMBOL-LIKE NUMBER VARIABLES IN AR- T...,4.75,3.25,2.75,3.00,2.25,...,- Novel application of DAS to study the symbol...,- The idea that symbol-like variables can emer...,3.0,4.0,This paper explores how transformer models imp...,3.0,3.0,2.0,1. The paper furthers the body of work on inte...,Novelty concerns: it does not seem like this p...
4,zwuemuTiN8,TACD-GRU: Time-Aware Context-Dependent Autoreg...,"Ankitkumar Joshi, Milos Hauskrecht",Reject,TACD-GRU: TIME-AWARE CONTEXT-DEPENDENT AU- TOR...,5.25,3.50,2.50,2.75,2.00,...,Handling sporadically observed time series is ...,Some of the standard deviations are extremely ...,6.0,3.0,This work proposes a dual model named TACD-GRU...,3.0,3.0,2.0,1. The paper is well-structured and clearly wr...,"1. Despite the simplicity, the context-based p..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5014,04RGjODVj3,From Rest to Action: Adaptive Weight Generatio...,"Param Rajpura, Yogesh Kumar Meena",Reject,FROM REST TO ACTION: ADAPTIVE WEIGHT GENERATIO...,3.00,4.75,2.00,1.25,1.75,...,The paper is original in that they apply a Hyp...,1. Claims on the strength of HyperNet + EEGNet...,1.0,5.0,"In this paper, the authors proposed a HyperEEG...",1.0,1.0,1.0,This study try to address the important issue ...,There is no substantial innovation in proposed...
5015,02kZwCo0C3,SAIL: Self-improving Efficient Online Alignmen...,"Mucong Ding, Souradip Chakraborty, Vibhu Agraw...",Reject,SAIL: Self-improving Efficient Online Alignmen...,5.75,3.75,3.25,3.00,3.25,...,1. Introducing Bi-level Preference Optimizatio...,Regarding the three variants of the SAIL metho...,6.0,4.0,"Compared to offline RLHF methods, online RLHF ...",3.0,2.0,4.0,* The authors test of two LLM-as-a-Judge bench...,"* As a practitioner, at least the presentation..."
5016,02Od16GFRW,Ensembles provably learn equivariance through ...,"Oskar Nordenfors, Axel Flinth",Reject,ENSEMBLES PROVABLY LEARN EQUIVARIANCE THROUGH ...,5.00,3.33,3.00,2.67,2.33,...,- The work show the emergence of equivariant i...,I have several concerns over the usefulness of...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5017,01wMplF8TL,INSTRUCTION-FOLLOWING LLMS FOR TIME SERIES PRE...,"Yu Meng, Malik Tiomoko",Reject,INSTRUCTION-FOLLOWING LLMS FOR TIME SERIES PRE...,4.50,3.25,2.25,2.25,2.50,...,- A novel two-stage framework for integrating ...,- **Technical Contributions are Incremental** ...,5.0,3.0,The article describe a new model to incorporat...,3.0,2.0,3.0,1. It is good that zero shot examples of descr...,1. There seems to be a mismatch between the de...
5018,00ezkB2iZf,MedFuzz: Exploring the Robustness of Large Lan...,"Robert Ness, Katie Matton, Hayden Helm, Sheng ...",Reject,MEDFUZZ: EXPLORING THE ROBUSTNESS OF LARGE LAN...,4.25,4.00,2.75,2.75,2.75,...,•\tClarity: The paper is well written and easy...,"•\tIn the case of MedQA dataset, the authors h...",3.0,4.0,This paper investigates the robustness of larg...,2.0,2.0,2.0,+ This paper examines the robustness of LLMs i...,+ A major weakness of this paper is the faithf...

In [47]:
df_sample = df_rejected.sample(n=10)
df_sample

,paper_id,title,authors,decision,paper_text,avg_rating,avg_confidence,avg_soundness,avg_presentation,avg_contribution,...,review_3_strengths,review_3_weaknesses,review_4_rating,review_4_confidence,review_4_summary,review_4_soundness,review_4_presentation,review_4_contribution,review_4_strengths,review_4_weaknesses
4127,BapOwAzicb,HOGT: High-Order Graph Transformers,"Xueqi Ma, Xingjun Ma, Chuang Liu, Sarah Monaza...",Reject,HOGT: HIGH-ORDER GRAPH TRANSFORMERS Anonymous ...,5.25,3.00,2.75,3.25,2.75,...,"(1) The paper introduces a novel approach, HOG...",(1) Domain Limitation of Datasets. Expanding t...,6.0,2.0,This paper introduces HOGT (High-Order Graph T...,3.0,3.0,3.0,1. The paper introduces a well-founded archite...,1. The strict hierarchy in the three-step mess...
213,xHGL9XqR8Y,The Wisdom of a Crowd of Brains: A Universal B...,"Roman Beliy, navve wasserman, Amit Zalcher, mi...",Reject,THE WISDOM OF A CROWD OF BRAINS: A UNIVERSAL B...,6.25,4.00,2.75,3.50,3.00,...,- This is a very strong and well written paper...,I think the paper is lacking some exploration ...,3.0,5.0,This paper introduces a Universal fMRI Encoder...,2.0,3.0,2.0,1. The proposed Universal Brain-Encoder can ef...,1. The idea appears to closely resemble existi...
3358,KadOFOsUpQ,Which Attention Heads Matter for In-Context Le...,"Kayo Yin, Jacob Steinhardt",Reject,WHICH ATTENTION HEADS MATTER FOR IN-CONTEXT LE...,3.75,3.50,2.50,2.75,2.25,...,1. The paper investigates two influential idea...,1. One of the key findings of the paper is tha...,3.0,3.0,The paper studies the role of different attent...,2.0,2.0,2.0,- It is interesting to understand ICL capabili...,- I am not very convinced by the ablation meth...
676,rcdR97P2Mp,Towards continuous machine learning on periodi...,"Daniel Eric Widdowson, Vitaliy Kurlin",Reject,TOWARDS CONTINUOUS MACHINE LEARNING ON PERIODI...,4.50,2.50,2.75,3.25,2.75,...,The work presents novel representations for pe...,The authors proposes a procedurally constructe...,5.0,2.0,This is a new method for searching crystals. M...,1.0,3.0,3.0,This works showcases large speedups in compari...,The paper is not written for ML audience. The ...
4537,634kHJgaOL,ROBO-INSTRUCT: Simulator-Augmented Instruction...,"Zichao Hu, Junyi Jessy Li, Arjun Guha, Joydeep...",Reject,ROBO-INSTRUCT: SIMULATOR-AUGMENTED INSTRUC- TI...,4.75,3.25,2.50,3.00,2.25,...,"Clarity: The framework's purpose, components, ...",(1) The data augmentation approach seems somew...,6.0,2.0,The goal of this paper is to,4.0,4.0,2.0,Clarity. The authors did a phenomenal job desc...,Presentation. Focusing solely on open models a...
2389,WQy61tS53c,Deep Bayesian Filter for Bayes-Faithful Data A...,"Yuta Tarumi, Keisuke Fukuda, Shin-ichi Maeda",Reject,DEEP BAYESIAN FILTER FOR BAYES-FAITHFUL DATA A...,5.50,3.50,2.50,2.50,2.25,...,Designing generic-purpose VAE for modeling tim...,No idea of the computation time for the propos...,6.0,4.0,This paper deals with data assimilation in gen...,3.0,3.0,2.0,"The idea of learning a Gaussian, NN-parameteri...","As far as I am concerned, the proposed methodo..."
658,rqBc4WnvUP,Multi-view Object-Centric Learning with Identi...,"Avinash Kori, Francesca Toni, Ben Glocker",Reject,MULTI-VIEW OBJECT-CENTRIC LEARNING WITH IDENTI...,3.50,3.75,2.25,2.50,2.25,...,1.\tThis paper extends PSA from a single-view ...,1.\tThis paper seems to simply apply the PSA f...,5.0,3.0,This paper proposes a multi-view probabilistic...,3.0,3.0,3.0,1. The paper provides identifiability guarante...,1. The use of the Expectation-Maximization (EM...
2786,RKB4WiesB4,Unsupervised Reinforcement Learning by Maximiz...,"Jiakun Zheng, Ting Xiao, Rushuai Yang, Kang Xu...",Reject,UNSUPERVISED REINFORCEMENT LEARNING BY MAXIMIZ...,5.00,3.50,2.75,2.75,2.25,...,"In general, this paper is well-written and eas...",The paper presents interesting contributions b...,5.0,4.0,This paper proposes an unsupervised reinforcem...,3.0,3.0,2.0,1. The presentation and writing of this paper ...,1. Experiments are not convincing enough. The ...
4785,2fZ9iOVzpR,A Study of Posterior Stability for Time-Series...,"Yangming Li, Yixin Cheng, Mihaela van der Schaar",Reject,A STUDY OF POSTERIOR STABILITY FOR TIME-SERIES...,5.25,3.25,2.50,2.50,2.25,...,The study of the latent diffusion model when a...,1. The experimental results mainly focus on re...,3.0,4.0,This paper addresses the issue of posterior co...,2.0,2.0,2.0,--The paper tries to focus on the specific iss...,--The problem is not sufficiently well motivat...
4539,62DvfHFesc,Longitudinal Latent Diffusion Models,"Meilame Tayebjee, Stephanie Allassonniere",Reject,LONGITUDINAL LATENT DIFFUSION MODELS Anonymous...,4.25,3.75,2.50,1.75,2.50,...,Longitudinal data arise naturally in numerous ...,"General design choices. In Introduction, autho...",3.0,4.0,This paper proposes the Longitudinal Latent Di...,3.0,1.0,2.0,1. LLDM presents a general framework for model...,"1. The paper is confusingly written, particula..."

In [48]:
# Caminho completo do arquivo
caminho = "../data/open_review_datasets_to_prompt_tests/iclr_2025_spotlight_rejected.csv"

# Cria o diretório se não existir
os.makedirs(os.path.dirname(caminho), exist_ok=True)

# Salva o DataFrame no CSV
df_sample.to_csv(caminho, index=False)